name: hello
version: 0.1.0.0
github: "mystilleef/hello"
license: GPL-3

author: "Lateef Alabi-Oki"
maintainer: "mystilleef@gmail.com"

copyright: "2020"

synopsis: Hello World
category: utility
homepage: https://github.com/bitemyapp/hello#readme
description: https://github.com/bitemyapp/hello#readme
extra-source-files: README.md

default-extensions:
  - Safe
  - NoImplicitPrelude
  - UnicodeSyntax
  - DerivingStrategies
  - NamedFieldPuns
  - RecordWildCards
  - NumericUnderscores
  - MultiWayIf
  - LambdaCase

dependencies:
  - base >=4.7 && <5

library:
  source-dirs: src
  when:
    - condition: false
      other-modules: Paths_hello
  ghc-options:
    - -j
    - -Weverything
    - -Wcompat
    - -Werror
    - -fno-safe-haskell
    - -Wno-unsafe
    - -Wno-prepositive-qualified-module
    - -Wno-missing-safe-haskell-mode

executables:
  hello-exe:
    main: Main.hs
    source-dirs: app
    when:
      - condition: false
        other-modules: Paths_hello
    ghc-options:
      - -Wno-missing-local-signatures
      - -Wno-prepositive-qualified-module
      - -fno-safe-haskell
      - -Wno-unsafe
      - -O2
      - -j
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hello

tests:
  hello-test:
    main: Spec.hs
    source-dirs: test
    when:
      - condition: false
        other-modules: Paths_hello
    ghc-options:
      - -Weverything
      - -Wcompat
      - -Werror
      - -Wno-prepositive-qualified-module
      - -Wno-missing-exported-signatures
      - -Wno-missing-safe-haskell-mode
      - -Wno-missing-import-lists
      - -Wno-missing-export-lists
      - -Wno-all-missed-specialisations
      - -fno-safe-haskell
      - -Wno-unsafe
      - -j
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hspec
      - QuickCheck
