resolver: lts-16.20
compiler-check: newer-minor
system-ghc: false
ghc-options:
  "$locals": -O2 -threaded -j -Wcompat -Werror
  "$targets": -O2 -threaded -j -Wall
  "$everything": -O2 -threaded -j

packages:
- '.'

